Setup
Victoria129/Air-Pollution pull request #1
Opened 2023-01-21 19:26 UTC by Victoria129

- I have added the following features to the application.
- [ ] Routing.
- [ ] Filtering.
- [ ] Styling.

2023-01-21 19:35 UTC, vickymarz requested changes
Hi @Victoria129 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that that does not have the Miroverse-provided readme template. Kindly add this[ readme](https://github.com/microverseinc/readme-template), and customize it to your project by adding relevant information about your project in all the readme sections. Please do not delete any section (the FAQ section is optional).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-21 20:10 UTC, afanimartin requested changes
Hi @Victoria129, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't use the recommended [readme](https://github.com/microverseinc/readme-template) template. The project also lacks litter checks. Please make the necessary changes.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-21 23:29 UTC, alexander16108 requested changes
Hi @Victoria129 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights

- Good commit history ✔️
- Good PR description ✔️
- Your README file is professional ✔️

## Required Changes ♻️
_Check the comments under the review._

- you should record a video presenting the features of the project.
- The maximum length of the video is 5 minutes.
- The video should contain a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
- The video should contain a demo of the project, highlighting all the project features.
- The video should contain a highlight about a piece of the code the student finds interesting or is proud of making.
- you should deploy the application using Heroku, Netlify, or GitHub Pages.
-  The project should be deployed properly, and the home and detail page works as expected.
-  A link to the deployed project is present in the README.
- The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 14:18 UTC, amejid reviewed
Hi @Victoria129, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional README. There are sections that are empty. Kindly fill them with relevant information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-17 14:18 UTC, amejid commented on README.md
> +</div>
- [ ] Please remove these lines as they are rendering a broken image.

![Screenshot from 2023-03-17 17-11-14](https://user-images.githubusercontent.com/17243325/225929295-a3b7d062-b097-4a73-a966-e0b7cae0c5a4.png)

2023-03-17 14:18 UTC, amejid commented on README.md
> +```
- [ ] These lines show an empty section.

![Screenshot from 2023-03-17 17-10-39](https://user-images.githubusercontent.com/17243325/225929751-b91a0d11-5b05-4c04-b873-258486cdbb32.png)

2023-03-17 14:18 UTC, amejid commented on README.md
> +```
Same thing here

![Screenshot from 2023-03-17 17-10-51](https://user-images.githubusercontent.com/17243325/225930028-619ddac7-38ed-4698-b645-bc33f6687ed6.png)

2023-03-17 14:18 UTC, amejid commented on README.md
> +
The Acknowledgment section is empty, I think you should mention the author of the original design here.

![Screenshot from 2023-03-17 17-09-26](https://user-images.githubusercontent.com/17243325/225930421-bb58e0e5-3b4c-4da8-87ae-327b9d122f11.png)

2023-03-18 02:14 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @Victoria129 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that doesn't have linter checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-18 19:18 UTC, Abenezer-Tilahun requested changes
Hi @helina42  , 

Great job for implemented  the some of the project requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git-Flow.
✔️ Good commit messages
✔️ Professional READEME 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 19:18 UTC, Abenezer-Tilahun commented on src/pages/home-page.jsx
> +)
- [ ] As stated in the project requirement in the interaction part for the Home page it state that **Along with the category name, you will display some numeric values per category that come from the API.** So Kindly try to implemented it .
![Capture](https://user-images.githubusercontent.com/93598189/226130094-dd37dbfa-e691-44ca-9f6e-9a039ff13669.PNG)

- Your Project Home Page design 

![Capture](https://user-images.githubusercontent.com/93598189/226130192-85afd909-9a4f-46e0-8d7e-cd29964b4061.PNG)

- The design guidelines Home page 

![Capture](https://user-images.githubusercontent.com/93598189/226130284-bd24d3d6-8c1c-4cc3-b9f4-228f8ffc1ab0.PNG)

2023-03-18 19:18 UTC, Abenezer-Tilahun commented on src/pages/home-page.jsx
> +export default HomePage;
- [ ] As stated in the project requirement You should follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including: Colors (select one main color for your website), Typography: font face, size and weight, Layout: composition and space between elements. But I notice that your design is a little bit different from the design guidelines Kindly i recommend you to follow the design guidelines for the Homepage and adjust  **Colors (select one main color for your website**) you used 2 color for the body(rgb(221, 211, 211)) and the container(rgb(240, 91, 116)) and **Layout: composition and space between elements.** Just like the design guidelines 
- For the Home page the design guidelines has the following Layout: composition and space between elements, the category are adjust in the 2 columns with different color composition 
![Capture](https://user-images.githubusercontent.com/93598189/226131114-41e06719-0114-4b78-b4a2-42ffe9468d2a.PNG)

- Your Project design Look likes this 

![Capture](https://user-images.githubusercontent.com/93598189/226131303-821cd905-f517-4e95-84ea-9dd501e457c9.PNG)

2023-03-18 19:18 UTC, Abenezer-Tilahun commented on src/tests/cityCard.test.js
> +});
- [ ] Good job for Create integration tests for your application using the React Testing Library. But Kindly makes sure that your test cases are passing the requirement , So kindly fix it.

![Capture](https://user-images.githubusercontent.com/93598189/226131620-655f755e-4da3-4bf2-beef-04a546097361.PNG)

2023-03-24 20:02 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @Victoria129 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 20:02 UTC, codepantha commented on src/components/CityCard.jsx
> +    </div>
- [ ] Please let's try to stick to the design guidelines for the cards as shown in the image below 👇 
- [ ] Please put the arrow at the top-right of the card
### DESIGN GUIDELINE
![image](https://user-images.githubusercontent.com/46839548/227617710-52a9592c-126a-42bc-a890-73eef5510c55.png)

### YOUR DESIGN
![image](https://user-images.githubusercontent.com/46839548/227618345-d5f009a3-7635-4c77-9ec4-556b7b45d593.png)

2023-03-24 20:02 UTC, codepantha commented on src/pages/home-page.jsx
> +  // setContinent(continent)
- [ ] Please remove commented-out code as they make your codebase look cluttered 👍

2023-03-24 20:02 UTC, codepantha commented on src/components/Pollution.jsx
> +</>
- [ ] According to the design guideline, please place the "Go Back" button at the top in the form of a navigation
- [ ] In the navigation, also include a Microphone and Settings icon to be consistent with the design
### Design Guidelines
![image](https://user-images.githubusercontent.com/46839548/227624204-b55adaf5-62aa-4b81-958c-e56b6957e19f.png)
### Your Design
![image](https://user-images.githubusercontent.com/46839548/227624371-938cfc60-5803-4523-aac2-aabd5e81959c.png)

2023-03-25 14:49 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Victoria129,

#### Nice job making the required changes. Unfortunately, you missed some of them but you are almost there.

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-25 14:49 UTC, Omar-Muhamad commented on src/pages/home-page.jsx
> +)
- [ ] As requested by the previous reviewers, Kindly stick to the given design and fix the overflowing city cards on the home page, and It's supposed to be two columns only not 3 as you did.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/227724032-67ef9491-7064-4a73-af86-8d2b1e54b454.png)  | ![image](https://user-images.githubusercontent.com/68796232/227724027-846d6cf0-cff1-4edb-b341-5b0fa64cc837.png)  |

[Hint] I suggest using `display: grid;` like this:
```css
display: grid;
grid-template-columns: repeat(2, 1fr);
```

2023-03-25 14:49 UTC, Omar-Muhamad commented on src/components/Pollution.jsx
> +}
- [ ] As requested by the previous reviewers, Kindly stick to the given design and make your details page take the full width of the page and fix all elements' placement, widths, and margins to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/227724529-22868fbf-c611-48d4-8fd1-f1fabb58da26.png)  | ![image](https://user-images.githubusercontent.com/68796232/227724512-2c8c6131-f38c-4c25-8144-20cfa8318a3e.png)  |

2023-03-25 17:51 UTC, Ismailco approved these changes
### Hi @Victoria129, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

✔️ Make required changes
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-25 18:22 UTC, Victoria129 commented
Thank you so much! @Ismailco

2023-03-25 18:23 UTC, merged